"""Portable local video/measurement viewer. No network, coaching or signal treatment."""
import json


LABELS={'brake_on':'Début de freinage candidat','brake_off':'Fin de freinage candidate',
        'throttle_on':'Reprise des gaz candidate','throttle_off':'Coupure des gaz candidate',
        'brake_active_unbounded':'Frein actif, début inconnu',
        'throttle_active_unbounded':'Gaz actifs, début inconnu','gear_change':'Changement de rapport lu'}


def render_index(data):
    lap=data['lap'];summary=data['summary']
    lines=['# Perception M1 — un tour complet','',
        '**Expérimental : observations, pas diagnostic de conduite. Gate A FAIL ; coaching_eligible=false.**','',
        f"Tour HUD {lap['number']} ; frames {lap['start_frame']}–{lap['end_frame']-1}, "
        f"temps vidéo [{lap['start_time_s']:.6f}, {lap['end_time_s']:.6f}[ s. "
        'Bornes du compteur confirmé, pas chronométrage physique certifié.','',
        '[Ouvrir le lecteur local](index.html). Vidéo et valeurs sont synchronisées par frame. '
        'Le dossier doit rester groupé pour que ses liens locaux fonctionnent.','',
        f"{summary['frames']} images, {len(data['zones'])} zones de navigation, "
        f"{len(summary['events'])} événements neutres candidats.",
        'Disponibilité : '+', '.join(f'{k} {v}/{summary["frames"]}' for k,v in summary['available'].items())+'.','',
        '## Zones du tour entier','',
        'Ces intervalles partitionnent chaque image, y compris les passages ordinaires. '
        'Leurs limites sont grossières, pas des repères physiques exacts.','',
        '| Zone | Temps vidéo, s | Frames, fin exclue |','| --- | --- | --- |']
    for z in data['zones']:
        lines.append(f"| {z['id']} — {z['label'].replace('|','/')} | {z['start_time_s']:.3f}–{z['end_time_s']:.3f} | {z['start_frame']}–{z['end_frame']} |")
    lines+=['','## Fenêtre temporelle détaillée','',
        f"[Vidéo du détail](video/detail.mp4) : {data['detail']['start_time_s']:g}–{data['detail']['end_time_s']:g}s.",
        f"{len(data['detail']['frames'])} images natives entre {data['detail']['sequence_start_s']:g} et "
        f"{data['detail']['sequence_end_s']:g}s ; pas demandé {data['detail']['requested_step_s']:g}s.",
        'Ces images ajoutent une chronologie ; elles ne constituent pas des annotations numériques nouvelles.','']
    lines += [f'![Séquence chronologique {i+1}]({p})' for i,p in enumerate(data['detail']['sheets'])]
    lines+=['','## Lecture par une IA','',
        'Ce fichier indexe les preuves. Une IA recevant le texte seul ne voit pas les vidéos '
        'ou images derrière leurs chemins. Joindre effectivement les planches demandées, '
        'ou employer un mode vidéo qui les traite réellement ; déclarer les pièces lues. '
        'La chronologie JSON et le lecteur local conservent tout le tour. '
        'Une fenêtre d’images détaillée ne vaut pas lecture visuelle exhaustive du tour.','',
        'Questions de perception : quel est l’ordre des actions dans la fenêtre ? '
        'Que montre la scène avant/après ? Quels détails ou intervalles restent inconnus ? '
        'Ne pas déduire une faute, une cause certaine, une trajectoire idéale ou un d métrique.','',
        '## Paramètres et limites','',
        f"Détection : {json.dumps(data['event_settings'],ensure_ascii=False)}.",
        'La date du candidat est conservée séparément de sa confirmation. Un état actif '
        'au début/après une lacune ne reçoit pas un début inventé. La persistance du '
        'détecteur ne constitue pas une précision de latence mesurée.','',
        *['- '+s for s in data['limitations']], '',
        'Le `d` et l’angle réel des roues sont indisponibles. Aucun nouvel OCR, '
        'aucun lissage ou remplissage de mesure. Les sources et artefacts restent inchangés.','']
    return '\n'.join(lines)


def render_viewer(data):
    view=dict(lap=data['lap'],zones=data['zones'],summary=data['summary'],samples=data['samples'],
        detail=data['detail'],settings=data['event_settings'],labels=LABELS)
    # JSON is data even when an input label contains HTML or a closing script tag.
    encoded=json.dumps(view,ensure_ascii=False,allow_nan=False,separators=(',',':')).replace('<','\\u003c')
    return VIEWER.replace('__PERCEPTION_DATA__',encoded)


VIEWER='''<!doctype html>
<html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Perception — un tour complet</title>
<style>
:root{color-scheme:light dark;--bg:light-dark(#f3f6f9,#111821);--paper:light-dark(#fff,#1a2532);--ink:light-dark(#1d2c40,#edf3f9);--muted:light-dark(#53667b,#b5c7db);--line:light-dark(#d5dfe9,#405165);--soft:light-dark(#e7eff7,#283a4d);--speed:light-dark(#bb6411,#ffbc69);--brake:light-dark(#c13b46,#ff9aa1);--gas:light-dark(#1a8551,#87e1b3);--cursor:light-dark(#234e83,#b4d3ff)}
*{box-sizing:border-box}body{font:15px/1.5 system-ui;margin:0;background:var(--bg);color:var(--ink)}main{max-width:1400px;margin:0 auto;padding:22px}h1{font-size:26px;font-weight:600;margin:0 0 5px}h2{font-size:18px;font-weight:600;margin:0 0 12px}p{margin:7px 0}.muted{color:var(--muted)}.header{margin-bottom:18px}.stage{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:15px}.panel{background:var(--paper);border:1px solid var(--line);border-radius:10px;padding:15px}video{width:100%;display:block;background:#000;border-radius:6px}.values{display:grid;grid-template-columns:1fr 1fr;gap:10px}.value{padding:10px;background:var(--soft);border-radius:6px}.value strong{font-size:25px;font-weight:500;display:block;font-variant-numeric:tabular-nums}.value span{font-size:12px;color:var(--muted)}.tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0}button,select{font:inherit;color:var(--ink);background:var(--paper);border:1px solid var(--line);padding:7px 10px;border-radius:5px;cursor:pointer}button[aria-pressed=true]{background:var(--soft)}input[type=range]{width:100%;accent-color:var(--cursor)}a{color:var(--cursor)}.overview{margin:15px 0}.zone-strip{display:flex;height:34px;border-radius:5px;overflow:hidden;border:1px solid var(--line)}.zone-strip button{min-width:0;padding:0;border:0;border-radius:0;font-size:10px;overflow:hidden;background:var(--soft)}.zone-strip button:nth-child(even){background:var(--paper)}.zone-strip button[aria-current=true]{background:var(--cursor);color:var(--bg)}.plot{min-width:0}.plot svg{display:block;width:100%;height:148px}.plot text{font:12px system-ui;fill:var(--ink)}.plot .frame,.plot .grid{stroke:var(--line);fill:none}.plot .grid{opacity:.4}.plot .cursor{stroke:var(--cursor);stroke-width:1.5}.plot .trace{fill:none;stroke-width:1.5}.plot .hit{fill:transparent;cursor:crosshair}.below{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-top:15px}.events{max-height:330px;overflow:auto}.event{display:block;text-align:left;width:100%;margin:5px 0;font-size:13px}.small{font-size:12px}.sheet{width:100%;height:auto;margin-top:12px}details{margin-top:14px}summary{cursor:pointer}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:7px;border-bottom:1px solid var(--line);text-align:left}#readout{font-variant-numeric:tabular-nums}#time-label{font-size:16px}#detail-native{max-width:100%;height:auto}.film-nav{display:flex;flex-wrap:wrap;gap:6px}.film-nav button{font-size:12px}.filelinks{display:flex;gap:14px;flex-wrap:wrap}.sync{font-size:12px;color:var(--muted);margin-top:10px}
@media(max-width:850px){.stage,.below{grid-template-columns:1fr}.values{grid-template-columns:repeat(4,1fr)}main{padding:12px}.value strong{font-size:21px}.zone-strip button{font-size:9px}.events{max-height:230px}}@media(max-width:450px){.values{grid-template-columns:1fr 1fr}.tools select{max-width:100%}}
</style>
<main>
<header class="header"><h1>Un tour, la scène et les commandes</h1><p id="lap-label"></p><p class="muted">M1 expérimental · événements neutres candidats · trajectoire latérale d indisponible · aucune analyse de faute</p></header>
<div class="stage"><section class="panel"><video id="video" controls preload="auto" src="video/lap.mp4"></video><div class="tools"><button id="prev" type="button">← 1 image</button><button id="next" type="button">1 image →</button><button id="full" type="button">Tout le tour</button><button id="detail" type="button">Détail Les Combes</button></div><label for="frame-slider" id="time-label">Image</label><input id="frame-slider" type="range" min="0" step="1"><p id="sync-status" class="sync"></p></section>
<aside class="panel"><h2>Image affichée</h2><p id="zone-label"></p><div class="values"><div class="value"><span>Vitesse · km/h</span><strong id="speed">—</strong></div><div class="value"><span>Frein · %</span><strong id="brake">—</strong></div><div class="value"><span>Gaz · %</span><strong id="gas">—</strong></div><div class="value"><span>Rapport</span><strong id="gear">—</strong></div></div><p class="muted small" id="quality"></p><p class="muted small">Lectures automatiques. Plein gaz souvent ≈94 % ; petits résidus et blips possibles. Le chiffre affiché ne prouve pas une action volontaire.</p></aside></div>
<section class="panel overview"><h2>Chronologie du tour entier</h2><div id="zone-strip" class="zone-strip" aria-label="Zones de navigation du tour"></div><div class="tools"><label for="zone-select">Zone</label><select id="zone-select"><option value="">Tout le tour / fenêtre libre</option></select><span id="range-label" class="muted small"></span></div><p class="muted small">Limites de zones approximatives, revues sur des vues de la source ; elles servent à naviguer et ne sont pas des repères de chronométrage.</p><div class="plot" id="speed-plot"></div><div class="plot" id="brake-plot"></div><div class="plot" id="gas-plot"></div><p class="muted small">Cliquer sur une courbe pour aller à cette image. Toutes les mesures du tour sont conservées, sans lissage ni raccord à travers les absences.</p></section>
<div class="below"><section class="panel"><h2>Événements neutres candidats</h2><p id="event-count" class="muted small"></p><div id="events" class="events"></div></section><section class="panel"><h2>Couverture et fichiers</h2><p id="coverage"></p><div class="filelinks"><a href="OBSERVATIONS.md">Index pour l’IA</a><a href="perception.json">Chronologie JSON</a><a href="samples.csv">Samples CSV</a><a href="video/detail.mp4">Clip détaillé</a></div><details><summary>Intervalles sans mesure fraîche</summary><div id="missing"></div></details><details><summary>Définitions, qualité et synchronisation</summary><p id="settings"></p><p>Les transitions sont datées à la première image candidate, avec la confirmation conservée séparément. Un état déjà actif au début ou après un trou reste sans début connu. Ce sont des événements du décodeur, pas des diagnostics.</p><p>Vidéo rendue sans changement de résolution/cadence : image locale i = image source de début + i. Lorsque le navigateur fournit le temps de l’image décodée, le curseur et les valeurs suivent ce temps. Le mode de secours suit l’horloge de lecture et reste approximatif.</p><p>Gate A FAIL ; coaching_eligible=false. Les limites des mesures et le caractère estimé/non disponible des autres champs restent explicites.</p></details></section></div>
<section class="panel" style="margin-top:15px"><h2>Séquence temporelle resserrée</h2><p id="sequence-label"></p><div id="film-nav" class="film-nav"></div><p id="image-info" class="muted small"></p><img id="detail-native" alt="Image native sélectionnée dans la fenêtre détaillée"><details><summary>Planches chronologiques à joindre réellement au modèle</summary><div id="sheets"></div><p class="muted small">Une IA recevant uniquement le texte ne voit pas les fichiers derrière les liens locaux. Les planches sont un échantillon temporel ; elles ne prouvent pas une revue exhaustive du tour ou des valeurs.</p></details></section>
</main>
<script id="perception-data" type="application/json">__PERCEPTION_DATA__</script>
<script>
(function(){'use strict';const data=JSON.parse(document.getElementById('perception-data').textContent),rows=data.samples,lap=data.lap,fps=60;const video=document.getElementById('video'),slider=document.getElementById('frame-slider');let index=0,range=[lap.start_time_s,lap.end_time_s];const NS='http://www.w3.org/2000/svg';
const el=id=>document.getElementById(id);const txt=(id,value)=>el(id).textContent=value;const number=v=>v===null?'—':Number(v).toFixed(1).replace(/\\.0$/,'');
slider.max=rows.length-1;txt('lap-label',`Tour HUD ${lap.number} · ${(lap.end_time_s-lap.start_time_s).toFixed(3)} s · ${rows.length} images · ${data.zones.length} zones · source ${lap.start_time_s.toFixed(3)}–${lap.end_time_s.toFixed(3)} s`);
function svgNode(name,attrs,parent,text){const n=document.createElementNS(NS,name);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;parent.appendChild(n);return n;}
function zoneAt(frame){return data.zones.find(z=>z.start_frame<=frame&&frame<z.end_frame);}
function update(i){index=Math.max(0,Math.min(rows.length-1,i));const r=rows[index],z=zoneAt(r.frame);slider.value=index;const value=f=>r.quality[f]==='observed'?number(r[f]):'—';txt('speed',value('speed_kmh'));txt('brake',value('brake_pct'));txt('gas',value('throttle_pct'));txt('gear',value('gear'));txt('time-label',`Source ${r.time_s.toFixed(3)} s · frame ${r.frame} · image du clip ${index}`);txt('zone-label',`${z.id} · ${z.label}`);txt('quality',['speed_kmh','brake_pct','throttle_pct'].map(f=>`${f}: ${r.quality[f]}${r[f]===null?' — '+r.reasons[f].join(', '):''}`).join(' · '));document.querySelectorAll('#zone-strip button').forEach(b=>b.setAttribute('aria-current',String(b.dataset.id===z.id)));document.querySelectorAll('.plot svg').forEach(s=>{const x=Number(s.dataset.left)+(r.time_s-range[0])/(range[1]-range[0])*Number(s.dataset.width);const c=s.querySelector('.cursor');c.setAttribute('x1',x);c.setAttribute('x2',x);c.style.display=r.time_s>=range[0]&&r.time_s<=range[1]?'':'none';});}
function seek(t){const i=Math.max(0,Math.min(rows.length-1,Math.round((t-lap.start_time_s)*fps)));video.pause();video.currentTime=(i+.05)/fps;update(i);}
function setRange(lo,hi,move){range=[lo,hi];const zone=data.zones.find(z=>Math.abs(z.start_time_s-lo)<1e-8&&Math.abs(z.end_time_s-hi)<1e-8);el('zone-select').value=zone?zone.id:'';drawAll();if(move)seek(lo);}
function plot(id,field,label,color){const host=el(id),w=host.clientWidth;if(w<1)return;host.replaceChildren();const h=148,l=58,r=14,top=22,b=43,pw=w-l-r,ph=h-top-b;const svg=svgNode('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':label+' en fonction du temps vidéo'},host);svg.dataset.left=l;svg.dataset.width=pw;const shown=rows.filter(v=>range[0]<=v.time_s&&v.time_s<=range[1]);let ymax=field==='speed_kmh'?Math.max(50,Math.ceil(Math.max(0,...shown.map(v=>v.quality[field]==='observed'?(v[field]||0):0))/50)*50):100;const x=t=>l+(t-range[0])/(range[1]-range[0])*pw,y=v=>top+ph-(v/ymax)*ph;svgNode('text',{x:l,y:14},svg,label);svgNode('rect',{x:l,y:top,width:pw,height:ph,class:'frame'},svg);for(let j=0;j<3;j++){const v=ymax*j/2;svgNode('line',{x1:l,x2:w-r,y1:y(v),y2:y(v),class:'grid'},svg);svgNode('text',{x:l-8,y:y(v)+4,'text-anchor':'end'},svg,String(v));}const ticks=w<450?3:5;for(let j=0;j<ticks;j++){const t=range[0]+(range[1]-range[0])*j/(ticks-1);svgNode('text',{x:x(t),y:h-b+18,'text-anchor':j===0?'start':j===ticks-1?'end':'middle'},svg,t.toFixed(1));}svgNode('text',{x:l+pw/2,y:h-5,'text-anchor':'middle'},svg,'Temps vidéo source (s)');let path='',open=false;for(const v of shown){if(v[field]===null||v.quality[field]!=='observed'){open=false;continue;}path+=(open?'L':'M')+x(v.time_s).toFixed(2)+','+y(v[field]).toFixed(2);open=true;}svgNode('path',{d:path,class:'trace',stroke:color},svg);svgNode('line',{x1:l,x2:l,y1:top,y2:top+ph,class:'cursor'},svg);const hit=svgNode('rect',{x:l,y:top,width:pw,height:ph,class:'hit'},svg);hit.addEventListener('click',event=>{const box=svg.getBoundingClientRect();const position=(event.clientX-box.left)*w/box.width;seek(range[0]+Math.max(0,Math.min(1,(position-l)/pw))*(range[1]-range[0]));});}
function drawAll(){plot('speed-plot','speed_kmh','Vitesse (km/h)','var(--speed)');plot('brake-plot','brake_pct','Frein (%)','var(--brake)');plot('gas-plot','throttle_pct','Gaz (%)','var(--gas)');txt('range-label',`Vue ${range[0].toFixed(3)}–${range[1].toFixed(3)} s`);update(index);}
for(const z of data.zones){const b=document.createElement('button');b.type='button';b.dataset.id=z.id;b.textContent=z.id.slice(1);b.title=z.label;b.setAttribute('aria-label',z.label);b.style.flex=String(z.end_frame-z.start_frame);b.addEventListener('click',()=>setRange(z.start_time_s,z.end_time_s,true));el('zone-strip').appendChild(b);const o=document.createElement('option');o.value=z.id;o.textContent=z.id+' · '+z.label;el('zone-select').appendChild(o);}
el('zone-select').addEventListener('change',()=>{const z=data.zones.find(z=>z.id===el('zone-select').value);if(z)setRange(z.start_time_s,z.end_time_s,true);else setRange(lap.start_time_s,lap.end_time_s,false);});el('full').addEventListener('click',()=>setRange(lap.start_time_s,lap.end_time_s,false));el('detail').addEventListener('click',()=>setRange(data.detail.start_time_s,data.detail.end_time_s,true));el('prev').addEventListener('click',()=>seek(rows[Math.max(0,index-1)].time_s));el('next').addEventListener('click',()=>seek(rows[Math.min(rows.length-1,index+1)].time_s));slider.addEventListener('input',()=>seek(rows[Number(slider.value)].time_s));
if('requestVideoFrameCallback' in video){txt('sync-status','Synchronisation : temps de présentation de l’image décodée.');const follow=(now,metadata)=>{update(Math.round(metadata.mediaTime*fps));video.requestVideoFrameCallback(follow);};video.requestVideoFrameCallback(follow);}else{txt('sync-status','Synchronisation de secours : horloge de lecture, correspondance visuelle approximative.');video.addEventListener('timeupdate',()=>update(Math.floor(video.currentTime*fps)));}
video.addEventListener('loadeddata',()=>update(Math.floor(video.currentTime*fps)));video.addEventListener('error',()=>txt('sync-status','Vidéo indisponible : conserver le dossier complet avec video/lap.mp4.'));
for(const e of data.summary.events){const b=document.createElement('button');b.className='event';b.type='button';const label=data.labels[e.type]||e.type;b.textContent=`${e.time_s.toFixed(3)} s · ${label} · ${e.zone_id}`;b.title=`Frame ${e.frame} ; confirmation ${e.confirmed_at_s.toFixed(3)} s ; ${e.reasons.join(', ')}`;b.addEventListener('click',()=>{setRange(Math.max(lap.start_time_s,e.time_s-3),Math.min(lap.end_time_s,e.time_s+3),false);seek(e.time_s);});el('events').appendChild(b);}txt('event-count',`${data.summary.events.length} candidats sur le tour entier. Une sélection d’événement ouvre son contexte ±3 s.`);txt('coverage',Object.entries(data.summary.available).map(([k,v])=>`${k}: ${v}/${rows.length}`).join(' · '));
for(const m of data.summary.missing){const p=document.createElement('p');p.className='small';p.textContent=`${m.field} · ${m.start_time_s.toFixed(3)}–${m.end_time_s.toFixed(3)} s · ${m.frames} images`;el('missing').appendChild(p);}if(!data.summary.missing.length)txt('missing','Aucun intervalle manquant sur ces quatre champs dans le tour.');txt('settings',`Seuil actif ${data.settings.on_pct} %, seuil inactif ${data.settings.off_pct} %, persistance ${data.settings.persistence_s} s, rupture au-delà de ${data.settings.max_gap_s} s.`);
function showImage(row){el('detail-native').src=row.image;txt('image-info',`Frame source ${row.frame} · ${row.time_s.toFixed(3)} s · vitesse ${number(row.values.speed_kmh)} km/h, frein ${number(row.values.brake_pct)} %, gaz ${number(row.values.throttle_pct)} % — valeurs automatiques.`);document.querySelectorAll('#film-nav button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.frame)===row.frame)));seek(row.time_s);}
for(const row of data.detail.frames){const b=document.createElement('button');b.type='button';b.dataset.frame=row.frame;b.textContent=row.time_s.toFixed(1)+' s';b.addEventListener('click',()=>showImage(row));el('film-nav').appendChild(b);}for(const sheet of data.detail.sheets){const a=document.createElement('a');a.href=sheet;const im=document.createElement('img');im.src=sheet;im.alt='Planche chronologique de frames source';im.className='sheet';a.appendChild(im);el('sheets').appendChild(a);}txt('sequence-label',`${data.detail.frames.length} images natives entre ${data.detail.sequence_start_s} et ${data.detail.sequence_end_s} s, pas demandé ${data.detail.requested_step_s} s. Cliquer pour afficher une image et placer le lecteur au même instant.`);const first=data.detail.frames[0];el('detail-native').src=first.image;txt('image-info',`Aperçu de la séquence : frame ${first.frame} à ${first.time_s.toFixed(3)} s. Sélectionner un bouton pour synchroniser le lecteur.`);
new ResizeObserver(drawAll).observe(el('speed-plot'));drawAll();
})();
</script></html>'''
